// Produktdaten: offizielle Nährwerte pro Portion, recherchiert am 2026-10-02.
// Felder: kcal, protein (g), kh = Kohlenhydrate (g), fett (g), dessert = KI-Einschätzung (manuell korrigierbar).
// Pro Produkt steht die Quelle als Kommentar (für die Stichprobenprüfung).
const produkte = [
  // ===== McDonald's =====
  { name: "Der M", kette: "McDonald's", kcal: 1071, protein: 59, kh: 52, fett: 68.7, dessert: false }, // Quelle: mcdonalds.at/produkt/der-m (Nährwerte pro Portion)
  { name: "Big Tasty Bacon", kette: "McDonald's", kcal: 666, protein: 33, kh: 35, fett: 43.6, dessert: false }, // Quelle: mcdonalds.at/produkt/big-tasty-bacon (Nährwerte pro Portion)
  { name: "Big Tasty Chicken", kette: "McDonald's", kcal: 633, protein: 27, kh: 49, fett: 36.7, dessert: false }, // Quelle: mcdonalds.at/produkt/big-tasty-chicken (Nährwerte pro Portion)
  { name: "Tasty Junior", kette: "McDonald's", kcal: 365, protein: 15, kh: 27, fett: 21.9, dessert: false }, // Quelle: mcdonalds.at/produkt/tasty-junior-2 (Nährwerte pro Portion)
  { name: "Crispy Veggie Big Tasty", kette: "McDonald's", kcal: 570, protein: 22, kh: 48, fett: 31, dessert: false }, // Quelle: mcdonalds.at/produkt/crispy-veggie-big-tasty (Nährwerte pro Portion)
  { name: "McToast Deluxe", kette: "McDonald's", kcal: 217, protein: 11, kh: 27, fett: 6.9, dessert: false }, // Quelle: mcdonalds.at/produkt/mctoast-deluxe (Nährwerte pro Portion)
  { name: "Chicken Wings", kette: "McDonald's", kcal: 314, protein: 31, kh: 3.5, fett: 19.4, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-wings (Nährwerte pro Portion)
  { name: "Shrimps", kette: "McDonald's", kcal: 233, protein: 10, kh: 19, fett: 12.4, dessert: false }, // Quelle: mcdonalds.at/produkt/shrimps (Nährwerte pro Portion)
  { name: "Potato Stripes mittel", kette: "McDonald's", kcal: 534, protein: 5.2, kh: 57, fett: 30.7, dessert: false }, // Quelle: mcdonalds.at/produkt/potato-stripes-mittel (Nährwerte pro Portion)
  { name: "Potato Stripes groß", kette: "McDonald's", kcal: 682, protein: 6.6, kh: 73, fett: 39.2, dessert: false }, // Quelle: mcdonalds.at/produkt/potato-stripes-large (Nährwerte pro Portion)
  { name: "McMuffin Tasty Egg", kette: "McDonald's", kcal: 396, protein: 18, kh: 30, fett: 22.1, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-tasty-egg (Nährwerte pro Portion)
  { name: "Kakao-Himbeer-Vanille Tasche", kette: "McDonald's", kcal: 246, protein: 2.7, kh: 29, fett: 12.9, dessert: true }, // Quelle: mcdonalds.at/produkt/kakao-himbeer-vanille-tasche (Nährwerte pro Portion)
  { name: "McSundae Himbeer", kette: "McDonald's", kcal: 231, protein: 3.5, kh: 45, fett: 4.2, dessert: true }, // Quelle: mcdonalds.at/produkt/mcsundae-himbeer (Nährwerte pro Portion)
  { name: "McSundae Weiße Schoko", kette: "McDonald's", kcal: 339, protein: 5, kh: 41, fett: 17.3, dessert: true }, // Quelle: mcdonalds.at/produkt/mcsundae-weisse-schoko (Nährwerte pro Portion)
  { name: "McFlurry Snickers", kette: "McDonald's", kcal: 306, protein: 7.1, kh: 41, fett: 12.5, dessert: true }, // Quelle: mcdonalds.at/produkt/mcflurry-snickers (Nährwerte pro Portion)
  { name: "Hafer-Zimt Cookie", kette: "McDonald's", kcal: 344, protein: 3.8, kh: 50, fett: 13.6, dessert: true }, // Quelle: mcdonalds.at/produkt/hafer-zimt-cookie (Nährwerte pro Portion)
  { name: "Cookie Dough Donut", kette: "McDonald's", kcal: 354, protein: 4.8, kh: 36, fett: 20.5, dessert: true }, // Quelle: mcdonalds.at/produkt/cookie-dough-donut (Nährwerte pro Portion)
  { name: "McPops Lotus Biscoff", kette: "McDonald's", kcal: 127, protein: 1.4, kh: 13, fett: 7.7, dessert: true }, // Quelle: mcdonalds.at/produkt/mcpops-lotus-biscoff (Nährwerte pro Portion)
  { name: "Himbeer-Schoko Brownie", kette: "McDonald's", kcal: 308, protein: 4.2, kh: 36, fett: 15.6, dessert: true }, // Quelle: mcdonalds.at/produkt/himbeer-schoko-brownie-2 (Nährwerte pro Portion)
  { name: "Matcha-Strawberry Torte", kette: "McDonald's", kcal: 330, protein: 4.4, kh: 32, fett: 20.6, dessert: true }, // Quelle: mcdonalds.at/produkt/matcha-strawberry-torte (Nährwerte pro Portion)
  { name: "Carrot Cake", kette: "McDonald's", kcal: 348, protein: 4.3, kh: 30, fett: 23.3, dessert: true }, // Quelle: mcdonalds.at/produkt/carrot-cake (Nährwerte pro Portion)
  { name: "Big Mac", kette: "McDonald's", kcal: 544, protein: 27, kh: 42, fett: 29, dessert: false }, // Quelle: mcdonalds.at/produkt/big-mac (Nährwerte pro Portion)
  { name: "Bacon Hamburger Royal mit Käse", kette: "McDonald's", kcal: 627, protein: 42, kh: 37, fett: 34, dessert: false }, // Quelle: mcdonalds.at/produkt/baconhamburger-royal-mit-kaese (Nährwerte pro Portion)
  { name: "Fresh Beef Wrap", kette: "McDonald's", kcal: 494, protein: 26, kh: 35, fett: 27, dessert: false }, // Quelle: mcdonalds.at/produkt/fresh-beef-wrap (Nährwerte pro Portion)
  { name: "Guacamole Salsa Beef Wrap", kette: "McDonald's", kcal: 494, protein: 26, kh: 40, fett: 25, dessert: false }, // Quelle: mcdonalds.at/produkt/guacamole-salsa-beef-wrap (Nährwerte pro Portion)
  { name: "Double Cheeseburger", kette: "McDonald's", kcal: 457, protein: 27, kh: 31, fett: 24, dessert: false }, // Quelle: mcdonalds.at/produkt/double-cheeseburger (Nährwerte pro Portion)
  { name: "Cheeseburger", kette: "McDonald's", kcal: 306, protein: 16, kh: 30, fett: 13, dessert: false }, // Quelle: mcdonalds.at/produkt/cheeseburger (Nährwerte pro Portion)
  { name: "Hamburger Royal mit Käse", kette: "McDonald's", kcal: 547, protein: 33, kh: 38, fett: 29, dessert: false }, // Quelle: mcdonalds.at/produkt/hamburger-royal-mit-kaese (Nährwerte pro Portion)
  { name: "Hamburger Royal TS", kette: "McDonald's", kcal: 452, protein: 27, kh: 36, fett: 21, dessert: false }, // Quelle: mcdonalds.at/produkt/hamburger-royal-ts (Nährwerte pro Portion)
  { name: "Hamburger", kette: "McDonald's", kcal: 258, protein: 13, kh: 29, fett: 9.4, dessert: false }, // Quelle: mcdonalds.at/produkt/hamburger (Nährwerte pro Portion)
  { name: "McCrispy CBO", kette: "McDonald's", kcal: 653, protein: 30, kh: 53, fett: 35, dessert: false }, // Quelle: mcdonalds.at/produkt/mccrispy-cbo (Nährwerte pro Portion)
  { name: "CBO Premium Chicken Wrap", kette: "McDonald's", kcal: 694, protein: 31, kh: 60, fett: 35.4, dessert: false }, // Quelle: mcdonalds.at/produkt/cbo-premium-chicken-wrap (Nährwerte pro Portion)
  { name: "Chicken McNuggets (6 Stk.)", kette: "McDonald's", kcal: 262, protein: 16, kh: 21, fett: 12, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-mcnuggets-6-stk (Nährwerte pro Portion)
  { name: "Guacamole Salsa Chicken Wrap", kette: "McDonald's", kcal: 501, protein: 24, kh: 53, fett: 21, dessert: false }, // Quelle: mcdonalds.at/produkt/guacamole-salsa-chicken-wrap (Nährwerte pro Portion)
  { name: "McCrispy", kette: "McDonald's", kcal: 582, protein: 26, kh: 50, fett: 30.1, dessert: false }, // Quelle: mcdonalds.at/produkt/mccrispy-highcrunch (Nährwerte pro Portion)
  { name: "Chickenburger", kette: "McDonald's", kcal: 280, protein: 9.4, kh: 41, fett: 8.6, dessert: false }, // Quelle: mcdonalds.at/produkt/chickenburger-2 (Nährwerte pro Portion)
  { name: "Double Chickenburger", kette: "McDonald's", kcal: 439, protein: 15, kh: 60, fett: 15, dessert: false }, // Quelle: mcdonalds.at/produkt/double-chickenburger-2 (Nährwerte pro Portion)
  { name: "McChicken", kette: "McDonald's", kcal: 415, protein: 19, kh: 45, fett: 17, dessert: false }, // Quelle: mcdonalds.at/produkt/mcchicken (Nährwerte pro Portion)
  { name: "McFish", kette: "McDonald's", kcal: 259, protein: 12, kh: 35, fett: 7.6, dessert: false }, // Quelle: mcdonalds.at/produkt/mcfish (Nährwerte pro Portion)
  { name: "Doppel Filet-o-Fish", kette: "McDonald's", kcal: 448, protein: 23, kh: 41, fett: 21, dessert: false }, // Quelle: mcdonalds.at/produkt/doppel-filet-o-fish (Nährwerte pro Portion)
  { name: "Filet-o-Fish", kette: "McDonald's", kcal: 327, protein: 15, kh: 36, fett: 14, dessert: false }, // Quelle: mcdonalds.at/produkt/filet-o-fish (Nährwerte pro Portion)
  { name: "Chicken McNuggets (20 Stk.)", kette: "McDonald's", kcal: 873, protein: 55, kh: 68, fett: 42, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-mcnuggets-20-stk (Nährwerte pro Portion)
  { name: "Chicken McNuggets (9 Stk.)", kette: "McDonald's", kcal: 393, protein: 25, kh: 31, fett: 19, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-mcnuggets-9-stk (Nährwerte pro Portion)
  { name: "Chicken McNuggets (4 Stk.)", kette: "McDonald's", kcal: 175, protein: 11, kh: 14, fett: 8.3, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-mcnuggets-4-stk (Nährwerte pro Portion)
  { name: "Fresh Chicken Wrap", kette: "McDonald's", kcal: 435, protein: 23, kh: 45, fett: 17, dessert: false }, // Quelle: mcdonalds.at/produkt/fresh-chicken-wrap (Nährwerte pro Portion)
  { name: "Pommes (groß)", kette: "McDonald's", kcal: 430, protein: 5.4, kh: 54, fett: 20, dessert: false }, // Quelle: mcdonalds.at/produkt/pommes-gross (Nährwerte pro Portion)
  { name: "Pommes (mittel)", kette: "McDonald's", kcal: 327, protein: 4.1, kh: 41, fett: 15, dessert: false }, // Quelle: mcdonalds.at/produkt/pommes-mittel (Nährwerte pro Portion)
  { name: "Pommes (klein)", kette: "McDonald's", kcal: 229, protein: 2.9, kh: 29, fett: 11, dessert: false }, // Quelle: mcdonalds.at/produkt/pommes-klein (Nährwerte pro Portion)
  { name: "Hashbrown", kette: "McDonald's", kcal: 141, protein: 1.7, kh: 17, fett: 7, dessert: false }, // Quelle: mcdonalds.at/produkt/hashbrown (Nährwerte pro Portion)
  { name: "Avocado & Egg Wrap", kette: "McDonald's", kcal: 613, protein: 31, kh: 35, fett: 37.9, dessert: false }, // Quelle: mcdonalds.at/produkt/avocado-egg-wrap (Nährwerte pro Portion)
  { name: "McMuffin Beef and Egg", kette: "McDonald's", kcal: 455, protein: 26, kh: 26, fett: 27, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-beef-and-egg (Nährwerte pro Portion)
  { name: "McMuffin Fresh Avocado", kette: "McDonald's", kcal: 388, protein: 16, kh: 27, fett: 24, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-fresh-avocado (Nährwerte pro Portion)
  { name: "McMuffin Beef", kette: "McDonald's", kcal: 347, protein: 19, kh: 26, fett: 18, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-beef (Nährwerte pro Portion)
  { name: "McMuffin Fresh Chicken", kette: "McDonald's", kcal: 335, protein: 14, kh: 35, fett: 15, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffinfresh-chicken-2 (Nährwerte pro Portion)
  { name: "McMuffin Cheese and Egg", kette: "McDonald's", kcal: 283, protein: 16, kh: 25, fett: 13, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-cheese-and-egg (Nährwerte pro Portion)
  { name: "McMuffin Bacon and Egg", kette: "McDonald's", kcal: 397, protein: 26, kh: 26, fett: 21, dessert: false }, // Quelle: mcdonalds.at/produkt/mcmuffin-bacon-and-egg (Nährwerte pro Portion)
  { name: "McToast Bacon-Käse", kette: "McDonald's", kcal: 230, protein: 9.6, kh: 28, fett: 8.6, dessert: false }, // Quelle: mcdonalds.at/produkt/mctoast-bacon-kaese (Nährwerte pro Portion)
  { name: "McToast Schinken-Käse", kette: "McDonald's", kcal: 212, protein: 9.3, kh: 28, fett: 6.7, dessert: false }, // Quelle: mcdonalds.at/produkt/mctoast-schinken-kaese (Nährwerte pro Portion)
  { name: "McToast Käse", kette: "McDonald's", kcal: 251, protein: 10, kh: 29, fett: 10, dessert: false }, // Quelle: mcdonalds.at/produkt/mctoast-kaese (Nährwerte pro Portion)
  { name: "Nougat Burger", kette: "McDonald's", kcal: 195, protein: 5, kh: 31, fett: 5.3, dessert: true }, // Quelle: mcdonalds.at/produkt/nougat-burger (Nährwerte pro Portion)
  { name: "Crunchy Müsli", kette: "McDonald's", kcal: 219, protein: 12, kh: 27, fett: 6.3, dessert: false }, // Quelle: mcdonalds.at/produkt/crunchy-muesli (Nährwerte pro Portion)
  { name: "Eierspeis", kette: "McDonald's", kcal: 288, protein: 22, kh: 1.2, fett: 22, dessert: false }, // Quelle: mcdonalds.at/produkt/eierspeis (Nährwerte pro Portion)
  { name: "Kornspitz", kette: "McDonald's", kcal: 175, protein: 7.1, kh: 29, fett: 2.6, dessert: false }, // Quelle: mcdonalds.at/produkt/kornspitz (Nährwerte pro Portion)
  { name: "Semmel", kette: "McDonald's", kcal: 165, protein: 5.9, kh: 32, fett: 1, dessert: false }, // Quelle: mcdonalds.at/produkt/semmel (Nährwerte pro Portion)
  { name: "Crispy Veggie Burger", kette: "McDonald's", kcal: 425, protein: 19, kh: 46, fett: 17.3, dessert: false }, // Quelle: mcdonalds.at/produkt/crispy-veggie-burger (Nährwerte pro Portion)
  { name: "Guacamole Salsa Crispy Veggie Wrap", kette: "McDonald's", kcal: 461, protein: 21, kh: 53, fett: 16.5, dessert: false }, // Quelle: mcdonalds.at/produkt/guacamole-salsa-crispy-veggie-wrap (Nährwerte pro Portion)
  { name: "Crispy Veggie Wrap", kette: "McDonald's", kcal: 461, protein: 21, kh: 48, fett: 18.9, dessert: false }, // Quelle: mcdonalds.at/produkt/crispy-veggie-wrap (Nährwerte pro Portion)
  { name: "Crispy Veggie Caesar Salat", kette: "McDonald's", kcal: 316, protein: 20, kh: 25, fett: 13.5, dessert: false }, // Quelle: mcdonalds.at/produkt/crispy-veggie-caesar-salat (Nährwerte pro Portion)
  { name: "Backhendl Salat", kette: "McDonald's", kcal: 366, protein: 18, kh: 40, fett: 14.3, dessert: false }, // Quelle: mcdonalds.at/produkt/backhendl-salat (Nährwerte pro Portion)
  { name: "Crispy Veggie Salat Backhendl-Style", kette: "McDonald's", kcal: 323, protein: 15, kh: 39, fett: 10.2, dessert: false }, // Quelle: mcdonalds.at/produkt/crispy-veggie-salat-backhendl-style (Nährwerte pro Portion)
  { name: "Snack Salat", kette: "McDonald's", kcal: 10, protein: 0.7, kh: 1.6, fett: 0.1, dessert: false }, // Quelle: mcdonalds.at/produkt/snack-salat (Nährwerte pro Portion)
  { name: "Chicken Caesar Salat", kette: "McDonald's", kcal: 376, protein: 23, kh: 26, fett: 19, dessert: false }, // Quelle: mcdonalds.at/produkt/chicken-caesar-salat (Nährwerte pro Portion)
  { name: "Italienischer Salat", kette: "McDonald's", kcal: 161, protein: 8.5, kh: 6, fett: 11, dessert: false }, // Quelle: mcdonalds.at/produkt/italienischer-salat (Nährwerte pro Portion)
  { name: "Griechischer Salat", kette: "McDonald's", kcal: 161, protein: 8.5, kh: 6, fett: 11, dessert: false }, // Quelle: mcdonalds.at/produkt/griechischer-salat (Nährwerte pro Portion)
  { name: "Bio Fruchtpüree", kette: "McDonald's", kcal: 62, protein: 0.6, kh: 13, fett: 0.5, dessert: true }, // Quelle: mcdonalds.at/produkt/bio-fruchtpueree-abe (Nährwerte pro Portion)
  { name: "Karottensticks", kette: "McDonald's", kcal: 22, protein: 0.6, kh: 3.6, fett: 0.1, dessert: false }, // Quelle: mcdonalds.at/produkt/karottensticks (Nährwerte pro Portion)
  { name: "Bio Apfel", kette: "McDonald's", kcal: 73, protein: 0.4, kh: 16, fett: 0.5, dessert: false }, // Quelle: mcdonalds.at/produkt/bio-apfel (Nährwerte pro Portion)
  { name: "McFlurry Lotus Biscoff", kette: "McDonald's", kcal: 340, protein: 6.5, kh: 54, fett: 11, dessert: true }, // Quelle: mcdonalds.at/produkt/mcflurry-lotus-biscoff (Nährwerte pro Portion)
  { name: "McFlurry Schokodrops", kette: "McDonald's", kcal: 356, protein: 6.1, kh: 55, fett: 12, dessert: true }, // Quelle: mcdonalds.at/produkt/mcflurry-schokodrops (Nährwerte pro Portion)
  { name: "McFlurry Oreo", kette: "McDonald's", kcal: 242, protein: 5.2, kh: 38, fett: 7.4, dessert: true }, // Quelle: mcdonalds.at/produkt/mcflurry-oreo (Nährwerte pro Portion)
  { name: "Apfeltasche", kette: "McDonald's", kcal: 228, protein: 2.3, kh: 28, fett: 12, dessert: true }, // Quelle: mcdonalds.at/produkt/apfeltasche (Nährwerte pro Portion)
  { name: "McSundae Schoko", kette: "McDonald's", kcal: 278, protein: 5.5, kh: 45, fett: 8.2, dessert: true }, // Quelle: mcdonalds.at/produkt/mcsundae-schoko (Nährwerte pro Portion)
  { name: "Mini-Schokodrops-Eis", kette: "McDonald's", kcal: 226, protein: 4.3, kh: 35, fett: 7.4, dessert: true }, // Quelle: mcdonalds.at/produkt/mini-schokodrops-eis (Nährwerte pro Portion)
  { name: "McSundae Karamell", kette: "McDonald's", kcal: 286, protein: 4.7, kh: 53, fett: 6.1, dessert: true }, // Quelle: mcdonalds.at/produkt/mcsundae-karamell (Nährwerte pro Portion)
  { name: "McSundae ohne Topping", kette: "McDonald's", kcal: 141, protein: 3.6, kh: 23, fett: 3.7, dessert: true }, // Quelle: mcdonalds.at/produkt/mcsundae-ohne-topping (Nährwerte pro Portion)
  { name: "Schoko Donut", kette: "McDonald's", kcal: 248, protein: 3.6, kh: 32, fett: 11, dessert: true }, // Quelle: mcdonalds.at/produkt/schoko-donut (Nährwerte pro Portion)
  { name: "Pastel de Nata", kette: "McDonald's", kcal: 132, protein: 2.8, kh: 19, fett: 5.1, dessert: true }, // Quelle: mcdonalds.at/produkt/pastel-de-nata (Nährwerte pro Portion)
  { name: "Profiteroles", kette: "McDonald's", kcal: 271, protein: 2.9, kh: 23, fett: 18, dessert: true }, // Quelle: mcdonalds.at/produkt/profiteroles (Nährwerte pro Portion)
  { name: "Schoko-Mousse Torte", kette: "McDonald's", kcal: 441, protein: 6.8, kh: 37, fett: 30, dessert: true }, // Quelle: mcdonalds.at/produkt/schoko-mousse-torte (Nährwerte pro Portion)
  { name: "Marzipantorte", kette: "McDonald's", kcal: 365, protein: 6.1, kh: 40, fett: 19, dessert: true }, // Quelle: mcdonalds.at/produkt/marzipantorte (Nährwerte pro Portion)
  { name: "Cheesecake", kette: "McDonald's", kcal: 395, protein: 6.3, kh: 34, fett: 26, dessert: true }, // Quelle: mcdonalds.at/produkt/cheesecake (Nährwerte pro Portion)
  { name: "Schoko Kuchen", kette: "McDonald's", kcal: 601, protein: 5.6, kh: 56, fett: 39, dessert: true }, // Quelle: mcdonalds.at/produkt/schoko-kuchen (Nährwerte pro Portion)
  { name: "Erdbeer-Buttermilch Schnitte", kette: "McDonald's", kcal: 287, protein: 4.1, kh: 39, fett: 12, dessert: true }, // Quelle: mcdonalds.at/produkt/erdbeer-buttermilch-schnitte (Nährwerte pro Portion)
  { name: "Croissant Donut", kette: "McDonald's", kcal: 411, protein: 5, kh: 35, fett: 27, dessert: true }, // Quelle: mcdonalds.at/produkt/croissant-donut (Nährwerte pro Portion)
  { name: "McPops Strawberry", kette: "McDonald's", kcal: 120, protein: 1.7, kh: 12, fett: 7.3, dessert: true }, // Quelle: mcdonalds.at/produkt/mcpops-strawberry (Nährwerte pro Portion)
  { name: "McPops Stracciatella", kette: "McDonald's", kcal: 120, protein: 1.7, kh: 12, fett: 7.3, dessert: true }, // Quelle: mcdonalds.at/produkt/mcpops-stracciatella (Nährwerte pro Portion)
  { name: "McPops Chocolate", kette: "McDonald's", kcal: 113, protein: 1.7, kh: 10, fett: 7.1, dessert: true }, // Quelle: mcdonalds.at/produkt/mcpops-chocolate (Nährwerte pro Portion)
  { name: "Croissant", kette: "McDonald's", kcal: 183, protein: 3.6, kh: 21, fett: 9.1, dessert: false }, // Quelle: mcdonalds.at/produkt/croissant (Nährwerte pro Portion)
  { name: "Schoko Croissant", kette: "McDonald's", kcal: 320, protein: 5.3, kh: 38, fett: 17, dessert: true }, // Quelle: mcdonalds.at/produkt/schoko-croissant (Nährwerte pro Portion)
  { name: "Heidelbeer Muffin", kette: "McDonald's", kcal: 389, protein: 5.3, kh: 40, fett: 23, dessert: true }, // Quelle: mcdonalds.at/produkt/heidelbeer-muffin (Nährwerte pro Portion)
  { name: "Schoko Cookie", kette: "McDonald's", kcal: 332, protein: 4, kh: 38.7, fett: 17.6, dessert: true }, // Quelle: mcdonalds.at/produkt/schoko-cookie (Nährwerte pro Portion)
  { name: "Triple-Schoko Cookie", kette: "McDonald's", kcal: 367, protein: 3.9, kh: 46, fett: 18, dessert: true }, // Quelle: mcdonalds.at/produkt/triple-schoko-cookie (Nährwerte pro Portion)

  // ===== Burger King =====
  { name: "Toni Macaroni", kette: "Burger King", kcal: 1153, protein: 49, kh: 72, fett: 62, dessert: false }, // Quelle: burgerking.at/en/menu/picker-b20226c0-eae9-452f-adfe-8c140c1f1a65 (Abschnitt "The Royals", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Toni Macaroni Double", kette: "Burger King", kcal: 1337, protein: 76, kh: 73, fett: 83, dessert: false }, // Quelle: burgerking.at/en/menu/picker-a1adcf6d-cb8f-4396-b2d1-f444d80354d9 (Abschnitt "The Royals", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Harry", kette: "Burger King", kcal: 894.5, protein: 44.8, kh: 50.2, fett: 56, dessert: false }, // Quelle: burgerking.at/en/menu/picker-7993bf41-2aa4-4707-9b15-ea5aae610918 (Abschnitt "The Royals", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Harry Double", kette: "Burger King", kcal: 1337, protein: 76, kh: 73, fett: 83, dessert: false }, // Quelle: burgerking.at/en/menu/picker-90b1da02-5f28-4477-b123-ac70841a9996 (Abschnitt "The Royals", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Lover Beef", kette: "Burger King", kcal: 964, protein: 37, kh: 66, fett: 60, dessert: false }, // Quelle: burgerking.at/en/menu/picker-bf2f5aa3-8d77-428d-8252-21345dbeb1e0 (Abschnitt "Chili Cheese Lovers", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Lover Beef Double", kette: "Burger King", kcal: 962.9, protein: 43, kh: 69.6, fett: 55.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-9b7578e1-ff9e-4ade-ba2f-50bc37bb3fe9 (Abschnitt "Chili Cheese Lovers", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Lover Chicken", kette: "Burger King", kcal: 860.7, protein: 36.1, kh: 78.1, fett: 42.7, dessert: false }, // Quelle: burgerking.at/en/menu/picker-ddb862ca-965f-4159-84c8-dfa7b37d201f (Abschnitt "Chili Cheese Lovers", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "WHOPPER", kette: "Burger King", kcal: 600.3, protein: 28.5, kh: 46, fett: 32.9, dessert: false }, // Quelle: burgerking.at/en/menu/picker-32257f4a-6ecc-4fe0-b91e-72c8dfa4c704 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Whopper", kette: "Burger King", kcal: 832.8, protein: 49, kh: 46.2, fett: 49.7, dessert: false }, // Quelle: burgerking.at/en/menu/picker-11a0cf33-ff83-4970-a35a-0d68267acef1 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Triple Whopper", kette: "Burger King", kcal: 1124.2, protein: 71.71, kh: 51.71, fett: 68.48, dessert: false }, // Quelle: burgerking.at/en/menu/picker-e036e5df-415b-4c99-ab93-db9c2e7fa5ea (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Whopper Junior", kette: "Burger King", kcal: 327.9, protein: 13.3, kh: 31.8, fett: 16.4, dessert: false }, // Quelle: burgerking.at/en/menu/picker-61d4e0a0-046b-4ae9-8e02-7221e52cad1c (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Bacon King", kette: "Burger King", kcal: 890, protein: 55.8, kh: 44.3, fett: 53.2, dessert: false }, // Quelle: burgerking.at/en/menu/picker-7367f1fd-8c78-42c6-a82e-d726dbe30dd9 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Steakhouse Burger", kette: "Burger King", kcal: 762.9, protein: 32, kh: 58.6, fett: 43.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-dbb541e0-fbc8-49c4-9853-844973e1f0e0 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Steakhouse Burger", kette: "Burger King", kcal: 962.9, protein: 43, kh: 69.6, fett: 55.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-6042d2a8-ce81-4986-83e6-07fd54cf9190 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Big King", kette: "Burger King", kcal: 464.1, protein: 27.3, kh: 29.1, fett: 25.5, dessert: false }, // Quelle: burgerking.at/en/menu/picker-f260bc3b-8b55-4bd6-a586-28083e8737e4 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Big King XXL", kette: "Burger King", kcal: 935.1, protein: 56, kh: 47.5, fett: 56.7, dessert: false }, // Quelle: burgerking.at/en/menu/picker-6a204cdb-e408-4a22-a77c-cb2d0bd874df (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Extra Long Chili Cheese", kette: "Burger King", kcal: 651.5, protein: 35.7, kh: 39.5, fett: 38.1, dessert: false }, // Quelle: burgerking.at/en/menu/picker-a3a953e3-f23d-459e-9b6a-092afd5aecab (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Whopper Wrap", kette: "Burger King", kcal: 645.94, protein: 31.09, kh: 37.38, fett: 40.48, dessert: false }, // Quelle: burgerking.at/en/menu/picker-2d06184b-7e42-4995-80db-f4fbc97aaeb9 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Cheeseburger", kette: "Burger King", kcal: 433.3, protein: 25.9, kh: 32, fett: 22, dessert: false }, // Quelle: burgerking.at/en/menu/picker-462cc161-0ac0-47de-9908-a33c4f75b207 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Cheeseburger", kette: "Burger King", kcal: 303.5, protein: 15.4, kh: 31.5, fett: 12.6, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20463 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hamburger", kette: "Burger King", kcal: 260.9, protein: 13, kh: 31.2, fett: 9.3, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20461 (Abschnitt "Flame-grilled Beef", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chicken King", kette: "Burger King", kcal: 530, protein: 17, kh: 43.4, fett: 31.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-17dc6a2e-9806-45b9-80de-387ae4e5f869 (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Long Chicken", kette: "Burger King", kcal: 769, protein: 34, kh: 61, fett: 42, dessert: false }, // Quelle: burgerking.at/en/menu/picker-25908418-1ef4-47d5-98e8-94ef24ddd5ad (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Long Chicken", kette: "Burger King", kcal: 572.5, protein: 19.6, kh: 47, fett: 33.2, dessert: false }, // Quelle: burgerking.at/en/menu/picker-40a2fd08-59ac-4195-8b0f-1d87f0cc2819 (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Crispy Chicken", kette: "Burger King", kcal: 721, protein: 28, kh: 54, fett: 43, dessert: false }, // Quelle: burgerking.at/en/menu/picker-cadea7a0-4831-4d16-8429-b72ec9d84f68 (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Crispy Chicken", kette: "Burger King", kcal: 530, protein: 17, kh: 43.4, fett: 31.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-525c99e4-a34d-4103-af56-9c7a88a76c5f (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Crispy Chicken Wrap", kette: "Burger King", kcal: 502.9, protein: 17.5, kh: 48.3, fett: 25.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-6f44dc32-0731-428b-a7ac-2613c9075154 (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chicken Nuggets 9 Stk.", kette: "Burger King", kcal: 435.3, protein: 21, kh: 35.25, fett: 22.95, dessert: false }, // Quelle: burgerking.at/en/menu/picker-822000f3-c9dc-44fa-ae2e-f536dd8b660e (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Wings 9 Stk.", kette: "Burger King", kcal: 572.7, protein: 56.25, kh: 6.75, fett: 35.4, dessert: false }, // Quelle: burgerking.at/en/menu/picker-0b7f0226-735c-4c98-b605-f903c62bfd23 (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chicken Nugget Burger", kette: "Burger King", kcal: 392.7, protein: 12.2, kh: 44.9, fett: 18.1, dessert: false }, // Quelle: burgerking.at/en/menu/picker-e42bc6e6-ca04-4e4e-b61f-cf4f771bbd6d (Abschnitt "Chicken", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Crispy Chicken", kette: "Burger King", kcal: 530, protein: 17, kh: 43.4, fett: 31.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-3d4a5597-336e-4472-a8c2-68439812414c (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Double Crispy Chicken", kette: "Burger King", kcal: 530, protein: 17, kh: 43.4, fett: 31.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-cacfe958-e138-4de9-90fd-6a689b5f8ed1 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Crispy Chicken Wrap", kette: "Burger King", kcal: 502.9, protein: 17.5, kh: 48.3, fett: 25.8, dessert: false }, // Quelle: burgerking.at/en/menu/picker-2e18d0ae-0797-4461-b2c3-6c8220b00a05 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Whopper", kette: "Burger King", kcal: 578, protein: 21.4, kh: 47.2, fett: 32, dessert: false }, // Quelle: burgerking.at/en/menu/picker-508e5968-b315-452e-a759-b77e64e45ddf (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Double Plant-based Long Chicken", kette: "Burger King", kcal: 794.5, protein: 25.1, kh: 60.5, fett: 40.4, dessert: false }, // Quelle: burgerking.at/en/menu/picker-bfc15bb7-b601-4acf-90c1-22491b16bb69 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Long Chicken", kette: "Burger King", kcal: 594.5, protein: 16.1, kh: 51.5, fett: 33.4, dessert: false }, // Quelle: burgerking.at/en/menu/picker-b5ac7ca0-b035-45c1-8c72-67719b4672a9 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant based Long Curry Chicken", kette: "Burger King", kcal: 518.5, protein: 9.9, kh: 53.5, fett: 23.9, dessert: false }, // Quelle: burgerking.at/en/menu/picker-c94d0e58-e604-4c1f-9057-404ff8665ff0 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Nuggets 6 Stk.", kette: "Burger King", kcal: 243, protein: 7.9, kh: 21.5, fett: 12.9, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_54024 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant Based Nuggets 9 Stk.", kette: "Burger King", kcal: 365, protein: 11.9, kh: 32.3, fett: 19.4, dessert: false }, // Quelle: burgerking.at/en/menu/picker-f5974cbd-c15b-4d5e-8af9-7860bc5723d1 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant Based Nuggets 20 Stk.", kette: "Burger King", kcal: 810, protein: 26, kh: 72, fett: 43, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_54027 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Nugget Burger", kette: "Burger King", kcal: 339.83, protein: 8.46, kh: 39.78, fett: 15.06, dessert: false }, // Quelle: burgerking.at/en/menu/picker-ad68e143-d771-4288-8874-310c585e05fd (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Plant-based Wrap", kette: "Burger King", kcal: 485.1, protein: 11.1, kh: 60.6, fett: 21.3, dessert: false }, // Quelle: burgerking.at/en/menu/picker-f232e27a-f7f2-483f-82a3-c4c5afd142de (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Snack Salad", kette: "Burger King", kcal: 24.7, protein: 1.1, kh: 4.1, fett: 0.4, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_44863 (Abschnitt "Plant-based", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Pommes Regular", kette: "Burger King", kcal: 465.8, protein: 5.6, kh: 54.7, fett: 23.5, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20488 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Pommes King Size", kette: "Burger King", kcal: 586.3, protein: 7.1, kh: 68.1, fett: 29.5, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20487 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chicken Nuggets 6 Stk.", kette: "Burger King", kcal: 290.2, protein: 14, kh: 23.5, fett: 15.3, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20466 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chicken Nuggets 20 Stk.", kette: "Burger King", kcal: 967.3, protein: 46.7, kh: 78.3, fett: 51, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20507 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Wings 6 Stk.", kette: "Burger King", kcal: 381.8, protein: 37.5, kh: 4.5, fett: 23.6, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20562 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Wings 20 Stk.", kette: "Burger King", kcal: 1272.7, protein: 125, kh: 15, fett: 78.7, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20570 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Nuggets 5 Stk.", kette: "Burger King", kcal: 305, protein: 9, kh: 32.2, fett: 17, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20599 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Nuggets 10 pcs", kette: "Burger King", kcal: 610, protein: 18, kh: 64.4, fett: 34, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20575 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Chili Cheese Nuggets 20 Stk.", kette: "Burger King", kcal: 1220, protein: 36, kh: 128.8, fett: 68, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_65298 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Onion Rings 6 Stk.", kette: "Burger King", kcal: 194.6, protein: 3.2, kh: 23, fett: 7.9, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20458 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Onion Rings 9 Stk.", kette: "Burger King", kcal: 291.9, protein: 4.8, kh: 34.5, fett: 11.85, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20470 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Onion Rings 12 Stk.", kette: "Burger King", kcal: 389.2, protein: 6.4, kh: 46, fett: 15.8, dessert: false }, // Quelle: burgerking.at/en/menu/item-item_20459 (Abschnitt "King Snacks", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Fusion made with KITKAT", kette: "Burger King", kcal: 320.4, protein: 5.5, kh: 47.2, fett: 11.9, dessert: true }, // Quelle: burgerking.at/en/menu/item-eec8c67c-e887-48fd-8452-25472fca70b9 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Fusion Smarties", kette: "Burger King", kcal: 320.4, protein: 5.5, kh: 47.2, fett: 11.9, dessert: true }, // Quelle: burgerking.at/en/menu/item-7c64768f-23b3-4ce1-b3f8-2e6842fd9831 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Fusion Lion", kette: "Burger King", kcal: 320.4, protein: 5.5, kh: 47.2, fett: 11.9, dessert: true }, // Quelle: burgerking.at/en/menu/item-9c15e900-81bf-42a0-87c6-61126ee9e396 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Fusion Oreo", kette: "Burger King", kcal: 280.5, protein: 5.3, kh: 43.8, fett: 9.1, dessert: true }, // Quelle: burgerking.at/en/menu/item-cf70b125-18e6-417b-ab9c-beeb8e991d18 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Sundae Chocolate", kette: "Burger King", kcal: 213.6, protein: 4.1, kh: 38.4, fett: 4.6, dessert: true }, // Quelle: burgerking.at/en/menu/item-1fdbd524-b0f3-4f25-9d63-ae26ad37eed8 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Sundae Caramel", kette: "Burger King", kcal: 239.4, protein: 4.2, kh: 40.2, fett: 6.8, dessert: true }, // Quelle: burgerking.at/en/menu/item-46df5bd1-d798-4c30-98f0-989e43f3b311 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "King Sundae Strawberry", kette: "Burger King", kcal: 183.2, protein: 4, kh: 34.4, fett: 3.3, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_65308 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Eiswaffel", kette: "Burger King", kcal: 100.2, protein: 2.74, kh: 16.6, fett: 2.6, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_20495 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Blondie", kette: "Burger King", kcal: 418, protein: 7, kh: 45.5, fett: 22.9, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_20328 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Blondie mit Softeis", kette: "Burger King", kcal: 425.05, protein: 6.5, kh: 42.64, fett: 25.03, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_20329 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Brownie mit Eis", kette: "Burger King", kcal: 430.65, protein: 5.78, kh: 41.36, fett: 26.39, dessert: true }, // Quelle: burgerking.at/en/menu/item-e519dacc-7ad9-4685-9865-a0aaaeee265b (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Hot Brownie", kette: "Burger King", kcal: 437.6, protein: 6.2, kh: 44.9, fett: 25.3, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_20581 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Warme Belgische Waffel mit Eis und Schoko", kette: "Burger King", kcal: 271.8, protein: 3.4, kh: 32.3, fett: 14.1, dessert: true }, // Quelle: burgerking.at/en/menu/picker-e92b966c-7ed5-4d6e-90b2-d9dcc76e8a95 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)
  { name: "Donut", kette: "Burger King", kcal: 322.9, protein: 2.7, kh: 31.6, fett: 20.5, dessert: true }, // Quelle: burgerking.at/en/menu/item-item_20589 (Abschnitt "Sweet Kings", Dialog "Nutritional Information", Per serving, gelesen 2026-10-03)

  // ===== Subway =====
  { name: "Chicken Teriyaki (15cm)", kette: "Subway", kcal: 270, protein: 22, kh: 38, fett: 3.3, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Plant-based Chicken Teriyaki (15cm)", kette: "Subway", kcal: 289, protein: 19, kh: 42, fett: 4.3, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Chicken Fajita (15cm)", kette: "Subway", kcal: 250, protein: 21, kh: 36, fett: 2.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Rotisserie-Style Chicken/Pulled Chicken Breast (15cm)", kette: "Subway", kcal: 260, protein: 21, kh: 34, fett: 4, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Chicken Tandoori (15cm)", kette: "Subway", kcal: 388, protein: 26, kh: 39, fett: 14, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Tuna (15cm)", kette: "Subway", kcal: 334, protein: 20, kh: 37, fett: 12, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Italian B.M.T. (15cm)", kette: "Subway", kcal: 369, protein: 21, kh: 36, fett: 16, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "BBQ Rib (15cm)", kette: "Subway", kcal: 474, protein: 23, kh: 38, fett: 26, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Nacho Chicken (15cm)", kette: "Subway", kcal: 415, protein: 19, kh: 47, fett: 17, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Philly Beef & Cheese (15cm)", kette: "Subway", kcal: 304, protein: 20, kh: 39, fett: 7.2, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Beef Chili (15cm)", kette: "Subway", kcal: 354, protein: 22, kh: 48, fett: 8, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "BBQ Pulled Pork (15cm)", kette: "Subway", kcal: 347, protein: 25, kh: 42, fett: 7.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Salami (15cm)", kette: "Subway", kcal: 254, protein: 12, kh: 35, fett: 7.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Ham (15cm)", kette: "Subway", kcal: 240, protein: 17, kh: 35, fett: 3.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Spicy Vegan Patty (15cm)", kette: "Subway", kcal: 301, protein: 21, kh: 44, fett: 9.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Veggie Delite (15cm)", kette: "Subway", kcal: 231, protein: 11, kh: 35, fett: 5.5, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Sandwich 15 cm
  { name: "Chicken Teriyaki Wrap", kette: "Subway", kcal: 372, protein: 20, kh: 54, fett: 7.1, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Plant-based Chicken Teriyaki Wrap", kette: "Subway", kcal: 391, protein: 17, kh: 58, fett: 8.1, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Chicken Fajita Wrap", kette: "Subway", kcal: 352, protein: 20, kh: 52, fett: 6.4, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Rotisserie-Style Chicken/Pulled Chicken Breast Wrap", kette: "Subway", kcal: 362, protein: 20, kh: 50, fett: 7.8, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Chicken Tandoori Wrap", kette: "Subway", kcal: 472, protein: 23, kh: 55, fett: 17, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Tuna Wrap", kette: "Subway", kcal: 436, protein: 19, kh: 53, fett: 16, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Italian B.M.T. Wrap", kette: "Subway", kcal: 454, protein: 19, kh: 52, fett: 18, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "BBQ Rib Wrap", kette: "Subway", kcal: 576, protein: 21, kh: 53, fett: 30, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Nacho Chicken Wrap", kette: "Subway", kcal: 530, protein: 18, kh: 62, fett: 22, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Philly Beef & Cheese Wrap", kette: "Subway", kcal: 406, protein: 19, kh: 55, fett: 11, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Beef Chili Wrap", kette: "Subway", kcal: 439, protein: 21, kh: 60, fett: 12, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Salami Wrap", kette: "Subway", kcal: 355, protein: 11, kh: 50, fett: 11, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Ham Wrap", kette: "Subway", kcal: 342, protein: 16, kh: 51, fett: 7.4, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Spicy Vegan Patty Wrap", kette: "Subway", kcal: 403, protein: 20, kh: 60, fett: 13, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Veggie Delite Wrap", kette: "Subway", kcal: 333, protein: 9.7, kh: 51, fett: 9.3, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Wrap
  { name: "Chicken Teriyaki Salat", kette: "Subway", kcal: 118, protein: 15, kh: 10, fett: 1.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Plant-based Chicken Teriyaki Salat", kette: "Subway", kcal: 137, protein: 12, kh: 14, fett: 2.6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Chicken Fajita Salat", kette: "Subway", kcal: 98, protein: 14, kh: 7.9, fett: 0.9, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Rotisserie-Style Chicken/Pulled Chicken Breast Salat", kette: "Subway", kcal: 109, protein: 15, kh: 6.4, fett: 2.2, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Chicken Tandoori Salat", kette: "Subway", kcal: 285, protein: 18, kh: 12, fett: 19, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Tuna Salat", kette: "Subway", kcal: 182, protein: 14, kh: 8.5, fett: 10, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Italian B.M.T. Salat", kette: "Subway", kcal: 200, protein: 14, kh: 7.5, fett: 13, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "BBQ Rib Salat", kette: "Subway", kcal: 271, protein: 14, kh: 7.2, fett: 20, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Nacho Chicken Salat", kette: "Subway", kcal: 337, protein: 13, kh: 20, fett: 23, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Philly Beef & Cheese Salat", kette: "Subway", kcal: 152, protein: 14, kh: 11, fett: 5.4, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Beef Chili Salat", kette: "Subway", kcal: 175, protein: 16, kh: 14, fett: 6, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Salami Salat", kette: "Subway", kcal: 101, protein: 5.3, kh: 6.4, fett: 5.9, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Ham Salat", kette: "Subway", kcal: 88, protein: 10, kh: 7.1, fett: 1.9, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Spicy Vegan Patty Salat", kette: "Subway", kcal: 149, protein: 15, kh: 16, fett: 7.8, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "Veggie Delite Salat", kette: "Subway", kcal: 79, protein: 4.5, kh: 6.5, fett: 3.8, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Salat
  { name: "The BBQ Master", kette: "Subway", kcal: 622, protein: 26, kh: 56, fett: 32, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Unsere Kreationen
  { name: "Furious Chicken", kette: "Subway", kcal: 522, protein: 27, kh: 50, fett: 23, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Unsere Kreationen
  { name: "Fiesta Fajita", kette: "Subway", kcal: 506, protein: 27, kh: 51, fett: 25, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Unsere Kreationen
  { name: "Tasty Tandoori", kette: "Subway", kcal: 388, protein: 26, kh: 39, fett: 14, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Unsere Kreationen
  { name: "Beef Texicana", kette: "Subway", kcal: 449, protein: 27, kh: 42, fett: 20, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Unsere Kreationen
  { name: "Beef Chili Baked Potato", kette: "Subway", kcal: 538, protein: 27, kh: 63, fett: 19, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Chicken Fajita Baked Potato", kette: "Subway", kcal: 547, protein: 27, kh: 54, fett: 24, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Nacho Chicken Baked Potato", kette: "Subway", kcal: 610, protein: 23, kh: 62, fett: 29, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Chicken Teriyaki Baked Potato", kette: "Subway", kcal: 577, protein: 32, kh: 56, fett: 24, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Dölicious Chicken", kette: "Subway", kcal: 634, protein: 34, kh: 59, fett: 30, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Rotisserie Style Chicken/Pulled Chicken Breast Baked Potato", kette: "Subway", kcal: 546, protein: 27, kh: 52, fett: 25, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Chicken Tandoori Baked Potato", kette: "Subway", kcal: 547, protein: 28, kh: 55, fett: 24, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Falafel Baked Potato", kette: "Subway", kcal: 588, protein: 18, kh: 65, fett: 29, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "BBQ Rib Baked Potato", kette: "Subway", kcal: 756, protein: 16, kh: 66, fett: 41, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Philly Beef & Cheese Baked Potato", kette: "Subway", kcal: 547, protein: 25, kh: 56, fett: 24, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Tuna Baked Potato", kette: "Subway", kcal: 620, protein: 27, kh: 54, fett: 33, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Salami Baked Potato", kette: "Subway", kcal: 547, protein: 19, kh: 52, fett: 29, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Italian BMT Baked Potato", kette: "Subway", kcal: 654, protein: 27, kh: 53, fett: 36, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 1, Baked Potato
  { name: "Ham Baked Potato", kette: "Subway", kcal: 526, protein: 23, kh: 53, fett: 24, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Veggie Delite Baked Potato", kette: "Subway", kcal: 490, protein: 16, kh: 54, fett: 23, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Plant-based Chicken Teriyaki Baked Potato", kette: "Subway", kcal: 575, protein: 25, kh: 60, fett: 25, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Plant-based Dölicious Chicken", kette: "Subway", kcal: 625, protein: 33, kh: 62, fett: 27, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Spicy Vegan Patty Baked Potato", kette: "Subway", kcal: 587, protein: 28, kh: 61, fett: 30, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Sour Cream Baked Potato", kette: "Subway", kcal: 585, protein: 22, kh: 55, fett: 31, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Baked Potato
  { name: "Chick'n'Garlic", kette: "Subway", kcal: 444, protein: 27, kh: 35, fett: 21, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Panini
  { name: "Philly Supreme", kette: "Subway", kcal: 441, protein: 25, kh: 40, fett: 20, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Panini
  { name: "Smoky Beast", kette: "Subway", kcal: 421, protein: 29, kh: 40, fett: 16, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Panini
  { name: "Peperoni-Salami & Cheese Footlong Dipper", kette: "Subway", kcal: 433, protein: 15, kh: 49, fett: 19, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Footlong Sidekicks
  { name: "Triple Cheese Footlong Dipper", kette: "Subway", kcal: 453, protein: 18, kh: 49, fett: 19, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Footlong Sidekicks
  { name: "Waffle Fries", kette: "Subway", kcal: 184, protein: 2.8, kh: 23, fett: 8.2, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Nacho Chicken Bites (1 Stück)", kette: "Subway", kcal: 45, protein: 2.6, kh: 3.5, fett: 2.1, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Mozzarella & Cheddar Bites x 5", kette: "Subway", kcal: 255, protein: 11, kh: 19, fett: 15, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Mozzarella & Cheddar Bites x 12", kette: "Subway", kcal: 612, protein: 26, kh: 45, fett: 36, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Coleslaw regular", kette: "Subway", kcal: 60, protein: 0.4, kh: 2.4, fett: 5.2, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Coleslaw Large", kette: "Subway", kcal: 119, protein: 0.8, kh: 4.8, fett: 10, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Lay’s Chips Salted", kette: "Subway", kcal: 148, protein: 1.7, kh: 14, fett: 9.4, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Lay’s Chips Paprika", kette: "Subway", kcal: 146, protein: 1.7, kh: 14, fett: 8.8, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Doritos Nacho Cheese", kette: "Subway", kcal: 220, protein: 2.9, kh: 26, fett: 11, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "Doritos Sweet Chili Pepper", kette: "Subway", kcal: 219, protein: 2.9, kh: 26, fett: 11, dessert: false }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Beilagen
  { name: "BuddyFruits Fruchtmousse", kette: "Subway", kcal: 56, protein: 0, kh: 1.7, fett: 12, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Getränke-Block (Fruchtmousse)
  { name: "Double Chocolate Cookie (vegan)", kette: "Subway", kcal: 209, protein: 2.3, kh: 27, fett: 9.5, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Chocolate Chunk Cookie", kette: "Subway", kcal: 214, protein: 2.3, kh: 28, fett: 10, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Chocolate Chip mit Rainbow Candy Cookie", kette: "Subway", kcal: 214, protein: 2.2, kh: 28, fett: 9.8, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "White Chip Macadamia Nut Cookie", kette: "Subway", kcal: 215, protein: 2.3, kh: 27, fett: 10, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Raspberry Cheesecake Cookie", kette: "Subway", kcal: 208, protein: 2.5, kh: 27, fett: 9.6, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Mini Chocolate Chip Cookies with Caramel Dip", kette: "Subway", kcal: 532, protein: 4.8, kh: 79, fett: 21, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Pumpkin Spiced Cookie", kette: "Subway", kcal: 194, protein: 2.29, kh: 26.9, fett: 8.3, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Matcha & White Chocolate Chip Cookie", kette: "Subway", kcal: 193, protein: 2.4, kh: 27.4, fett: 7.9, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies
  { name: "Brookie Cookie Cup", kette: "Subway", kcal: 266, protein: 2.7, kh: 28, fett: 13, dessert: true }, // Quelle: Subway Nährwertinformationen Deutschland Sept. 2026 (PDF), S. 2, Cookies

  // ===== Dunkin' Donuts =====
  { name: "Chocolate Lovers", kette: "Dunkin' Donuts", kcal: 360, protein: 5, kh: 43, fett: 19, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered White Chocolate", kette: "Dunkin' Donuts", kcal: 320, protein: 4, kh: 32, fett: 19, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Frosted White Chocolate", kette: "Dunkin' Donuts", kcal: 340, protein: 4, kh: 37, fett: 19, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Glazed Ring", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 25, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Chocolate Frosted Ring", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Chocolate Frosted with Sprinkles", kette: "Dunkin' Donuts", kcal: 250, protein: 3, kh: 30, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Caramel Frosted Ring", kette: "Dunkin' Donuts", kcal: 240, protein: 3, kh: 23, fett: 14, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Cinnamon Powdered Ring", kette: "Dunkin' Donuts", kcal: 210, protein: 3, kh: 21, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Strawberry Frosted Ring", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Strawberry Frosted Rainbow Sprinkle Ring", kette: "Dunkin' Donuts", kcal: 250, protein: 3, kh: 31, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Vanilla Frosted Ring", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Vanilla Frosted with Rainbow Sprinkles", kette: "Dunkin' Donuts", kcal: 250, protein: 3, kh: 31, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Caramel Frosted Ring with Chocolate Sprinkles", kette: "Dunkin' Donuts", kcal: 270, protein: 4, kh: 30, fett: 16, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Frosted Ring with Seasonal Color", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Sugared Raspberry Jelly Shell", kette: "Dunkin' Donuts", kcal: 250, protein: 3, kh: 31, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Boston Crème", kette: "Dunkin' Donuts", kcal: 280, protein: 4, kh: 33, fett: 15, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Bavarian Crème Shell", kette: "Dunkin' Donuts", kcal: 260, protein: 4, kh: 28, fett: 15, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Double Caramel", kette: "Dunkin' Donuts", kcal: 280, protein: 4, kh: 32, fett: 16, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Nougat Creme", kette: "Dunkin' Donuts", kcal: 290, protein: 4, kh: 30, fett: 17, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Sugared Nougat Creme", kette: "Dunkin' Donuts", kcal: 290, protein: 4, kh: 30, fett: 17, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Lemon Shell", kette: "Dunkin' Donuts", kcal: 260, protein: 3, kh: 31, fett: 14, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Frosted Lemon Shell", kette: "Dunkin' Donuts", kcal: 300, protein: 3, kh: 36, fett: 16, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Cinnamon Powdered Apple Shell", kette: "Dunkin' Donuts", kcal: 240, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Strawberry Shell", kette: "Dunkin' Donuts", kcal: 240, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Frosted Strawberry Shell", kette: "Dunkin' Donuts", kcal: 270, protein: 3, kh: 33, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Frosted Heart Shell", kette: "Dunkin' Donuts", kcal: 340, protein: 3, kh: 37, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Glazed Yeast Munchkin", kette: "Dunkin' Donuts", kcal: 50, protein: 1, kh: 6, fett: 2.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Yeast Munchkin", kette: "Dunkin' Donuts", kcal: 50, protein: 1, kh: 6, fett: 2.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Cinnamon Powdered Yeast Munchkin", kette: "Dunkin' Donuts", kcal: 50, protein: 1, kh: 6, fett: 2.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Sugared Jelly Filled Munchkin", kette: "Dunkin' Donuts", kcal: 50, protein: 1, kh: 7, fett: 2.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Bavarian Filled Munchkin", kette: "Dunkin' Donuts", kcal: 70, protein: 1, kh: 5, fett: 2.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Powdered Raspberry Filled Munchkin", kette: "Dunkin' Donuts", kcal: 60, protein: 1, kh: 7, fett: 3, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Smiley Face", kette: "Dunkin' Donuts", kcal: 290, protein: 3, kh: 34, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Chocolate orange", kette: "Dunkin' Donuts", kcal: 250, protein: 3, kh: 31, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Smiley Santa", kette: "Dunkin' Donuts", kcal: 290, protein: 3, kh: 34, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Green Christmas Star", kette: "Dunkin' Donuts", kcal: 280, protein: 3, kh: 37, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Red Christmas Star", kette: "Dunkin' Donuts", kcal: 280, protein: 3, kh: 37, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Apple Crumble", kette: "Dunkin' Donuts", kcal: 300, protein: 4, kh: 36, fett: 15, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Apple Cinamon", kette: "Dunkin' Donuts", kcal: 240, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Lemon ring with sprinkles", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Nougat Hazelnut crunch", kette: "Dunkin' Donuts", kcal: 350, protein: 4, kh: 39, fett: 19, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Strawberries & Cream", kette: "Dunkin' Donuts", kcal: 300, protein: 4, kh: 38, fett: 15, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Lemon Meringue", kette: "Dunkin' Donuts", kcal: 300, protein: 4, kh: 38, fett: 15, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Maple Iced", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 27, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Cookies and cream", kette: "Dunkin' Donuts", kcal: 300, protein: 4, kh: 37, fett: 16, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Cinammon Glazed", kette: "Dunkin' Donuts", kcal: 230, protein: 3, kh: 25, fett: 13, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Sugar Raised", kette: "Dunkin' Donuts", kcal: 220, protein: 3, kh: 24, fett: 12, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Double Chocolate", kette: "Dunkin' Donuts", kcal: 310, protein: 3, kh: 32, fett: 18, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Glazed chocolate munchkins", kette: "Dunkin' Donuts", kcal: 60, protein: 1, kh: 7, fett: 4, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Chocolate munchkins", kette: "Dunkin' Donuts", kcal: 70, protein: 1, kh: 5, fett: 3.5, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Glazed chocolate cake", kette: "Dunkin' Donuts", kcal: 310, protein: 3, kh: 32, fett: 18, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "chocolate coated munchkins", kette: "Dunkin' Donuts", kcal: 70, protein: 1, kh: 7, fett: 4, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Chocolate Cake", kette: "Dunkin' Donuts", kcal: 270, protein: 3, kh: 23, fett: 18, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)
  { name: "Old Fashioned", kette: "Dunkin' Donuts", kcal: 270, protein: 3, kh: 24, fett: 17, dessert: true }, // Quelle: neu.dunkindonuts.ch DD_Ingredients_Donuts.pdf, S. 1 (Donuts Nutrition Facts, 1 donut)

  // ===== KFC =====
  { name: "Zinger Dunked Burger", kette: "KFC", kcal: 571, protein: 32, kh: 54, fett: 24, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Highlights" (240,5 g)
  { name: "3 Hot Wings Dunked", kette: "KFC", kcal: 294, protein: 16, kh: 14, fett: 19, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Highlights" (108 g)
  { name: "2 Crispys Dunked", kette: "KFC", kcal: 226, protein: 16, kh: 13, fett: 12, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Highlights" (112 g)
  { name: "Spicy Teriyaki Double Crispy Burger", kette: "KFC", kcal: 468, protein: 24, kh: 44, fett: 22, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Deals" (ca. 220 g)
  { name: "Spicy Teriyaki Twister", kette: "KFC", kcal: 490, protein: 22, kh: 52, fett: 20, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Deals" (ca. 240 g)
  { name: "Crispy Chili Cheese Burger", kette: "KFC", kcal: 329, protein: 12, kh: 34, fett: 16, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (116 g)
  { name: "Colonel Original Burger", kette: "KFC", kcal: 567, protein: 29, kh: 49, fett: 28, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (243 g)
  { name: "Classic Original Burger", kette: "KFC", kcal: 494, protein: 26, kh: 48, fett: 21, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (205 g)
  { name: "Cheese & Bacon Burger", kette: "KFC", kcal: 593, protein: 34, kh: 47, fett: 29, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (239 g)
  { name: "Double Cheese & Bacon Burger", kette: "KFC", kcal: 861, protein: 56, kh: 57, fett: 44, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (346 g)
  { name: "Double Colonel Original Burger", kette: "KFC", kcal: 797, protein: 49, kh: 59, fett: 40, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (339 g)
  { name: "Kentucky BBQ Original Burger", kette: "KFC", kcal: 521, protein: 29, kh: 53, fett: 21, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (238 g)
  { name: "Double Kentucky BBQ Original Burger", kette: "KFC", kcal: 789, protein: 51, kh: 63, fett: 36, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (345 g)
  { name: "Classic Zinger Burger", kette: "KFC", kcal: 490, protein: 27, kh: 46, fett: 22, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (200 g)
  { name: "Kentucky BBQ Zinger Burger", kette: "KFC", kcal: 518, protein: 29, kh: 51, fett: 21, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (233 g)
  { name: "Double Kentucky BBQ Zinger Burger", kette: "KFC", kcal: 782, protein: 52, kh: 59, fett: 37, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (335 g)
  { name: "Colonel Veggie Burger", kette: "KFC", kcal: 506, protein: 19, kh: 50, fett: 24, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (229 g)
  { name: "Classic Veggie Burger", kette: "KFC", kcal: 433, protein: 16, kh: 48, fett: 18, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (191 g)
  { name: "Double Crispy Classic Burger", kette: "KFC", kcal: 399, protein: 20, kh: 38, fett: 18, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (167 g)
  { name: "Crispy Cheese Burger", kette: "KFC", kcal: 277, protein: 13, kh: 36, fett: 12, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Burger" (116 g)
  { name: "18 Hot Wings Chick & Share", kette: "KFC", kcal: 1620, protein: 96, kh: 72, fett: 102, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Buckets" (ca. 648 g)
  { name: "10 Crispys Chick & Share", kette: "KFC", kcal: 960, protein: 76, kh: 40, fett: 56, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Buckets" (ca. 400 g)
  { name: "3 Original Bites", kette: "KFC", kcal: 174, protein: 15, kh: 9, fett: 9, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (75 g)
  { name: "11 Hot Wings", kette: "KFC", kcal: 1826, protein: 110, kh: 66, fett: 121, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (ca. 572 g)
  { name: "6 Hot Wings", kette: "KFC", kcal: 996, protein: 60, kh: 36, fett: 66, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (ca. 312 g)
  { name: "3 Hot Wings", kette: "KFC", kcal: 498, protein: 30, kh: 18, fett: 33, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (156 g)
  { name: "3 Hähnchenteile", kette: "KFC", kcal: 801, protein: 60, kh: 25, fett: 43, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (ca. 315 g)
  { name: "2 Hähnchenteile", kette: "KFC", kcal: 528, protein: 40, kh: 16, fett: 28, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (ca. 207 g)
  { name: "1 Hähnchenteil", kette: "KFC", kcal: 264, protein: 16, kh: 11, fett: 18, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Chicken" (ca. 97 g)
  { name: "Crispy Twister", kette: "KFC", kcal: 500, protein: 22, kh: 54, fett: 22, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Wraps" (ca. 230 g)
  { name: "Crispy Veggie Twister", kette: "KFC", kcal: 460, protein: 16, kh: 56, fett: 18, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Veggie" (ca. 220 g)
  { name: "Original Bites Salad", kette: "KFC", kcal: 275, protein: 20, kh: 19, fett: 12, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Salate" (296 g)
  { name: "Veggie Tender Salad", kette: "KFC", kcal: 213, protein: 12, kh: 17, fett: 9, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Salate" (279 g)
  { name: "KFC Salat", kette: "KFC", kcal: 45, protein: 2, kh: 6, fett: 1, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Salate" (197 g)
  { name: "Chocolate Cookie", kette: "KFC", kcal: 352, protein: 4, kh: 46, fett: 17, dessert: true }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Desserts" (72 g)
  { name: "Double Chocolate Cookie", kette: "KFC", kcal: 346, protein: 4, kh: 44, fett: 17, dessert: true }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Desserts" (72 g)
  { name: "Cheese & Bacon Fries", kette: "KFC", kcal: 544, protein: 12, kh: 60, fett: 30, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (222 g)
  { name: "Cheese Fries Veggie", kette: "KFC", kcal: 475, protein: 9, kh: 59, fett: 24, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (207 g)
  { name: "Pommes frites, groß", kette: "KFC", kcal: 347, protein: 4, kh: 44, fett: 16, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (157 g)
  { name: "Pommes frites, klein", kette: "KFC", kcal: 239, protein: 3, kh: 30, fett: 11, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (108 g)
  { name: "Kartoffelpüree mit Gravy", kette: "KFC", kcal: 112, protein: 3, kh: 23, fett: 1, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (200 g)
  { name: "Halber Maiskolben", kette: "KFC", kcal: 139, protein: 5, kh: 24, fett: 3, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (125 g)
  { name: "Coleslaw", kette: "KFC", kcal: 255, protein: 2, kh: 16, fett: 20, dessert: false }, // Quelle: kfcmenupreise.de/kfc-kalorien-liste, Tabelle "Beilagen & Saucen" (150 g)
];
